#!/usr/bin/env ruby
require File.expand_path(File.join(__FILE__, '..', '..', '..', 'config', 'environment'))

require 'socketry/registrar'

Socketry.logger.level = Logger::DEBUG
Socketry.registrar.register
